spacex:
  target: prod_password
  outputs:
    # --- Password-based auth (simple) ---
    prod_password:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: analytics            # dbt target schema (create if not exists)
      threads: 4
      sslmode: prefer